[project]
name = 'stacks-pyth-network'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[contracts.pyth-governance-v3]
path = 'contracts/pyth-governance-v3.clar'
clarity_version = 3
epoch = 3.0

[contracts.pyth-oracle-v4]
path = 'contracts/pyth-oracle-v4.clar'
clarity_version = 3
epoch = 3.0

[contracts.pyth-storage-v4]
path = 'contracts/pyth-storage-v4.clar'
clarity_version = 3
epoch = 3.0

[contracts.pyth-pnau-decoder-v3]
path = 'contracts/pyth-pnau-decoder-v3.clar'
clarity_version = 3
epoch = 3.0

[contracts.pyth-traits-v2]
path = 'contracts/pyth-traits-v2.clar'
clarity_version = 3
epoch = 3.0

[contracts.wormhole-core-v4]
path = 'contracts/wormhole/wormhole-core-v4.clar'
clarity_version = 3
epoch = 3.0

[contracts.wormhole-traits-v2]
path = 'contracts/wormhole/wormhole-traits-v2.clar'
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
